name: Build and Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install pyinstaller rich click requests pyyaml
      - run: |
          pyinstaller --onefile --name upid-linux-x86_64 upid_main.py
      - run: |
          chmod +x ./dist/upid-linux-x86_64
          ./dist/upid-linux-x86_64 --help
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/upid-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install pyinstaller rich click requests pyyaml
      - run: |
          pyinstaller --onefile --name upid-darwin-arm64 upid_main.py
      - run: |
          chmod +x ./dist/upid-darwin-arm64
          ./dist/upid-darwin-arm64 --help
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/upid-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install pyinstaller rich click requests pyyaml
      - run: |
          pyinstaller --onefile --name upid-windows-x86_64 upid_main.py
      - run: |
          ./dist/upid-windows-x86_64.exe --help
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/upid-windows-x86_64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
