name: Build and Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64]
        include:
          - os: ubuntu-latest
            arch: aarch64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu \
                                  libc6-dev-arm64-cross \
                                  libssl-dev:arm64 \
                                  zlib1g-dev:arm64

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller rich click requests pyyaml

      - name: Build binary
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            pyinstaller --onefile --name upid-windows-x86_64 upid_main.py
          elif [ "${{ runner.os }}" = "macOS" ]; then
            pyinstaller --onefile --name upid-darwin-arm64 upid_main.py
          elif [ "${{ matrix.arch }}" = "aarch64" ]; then
            pyinstaller --onefile --name upid-linux-arm64 upid_main.py
          else
            pyinstaller --onefile --name upid-linux-x86_64 upid_main.py
          fi

      - name: Test binary
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            ./dist/upid-windows-x86_64.exe --help
          elif [ "${{ runner.os }}" = "macOS" ]; then
            chmod +x ./dist/upid-darwin-arm64
            ./dist/upid-darwin-arm64 --help
          elif [ "${{ matrix.arch }}" = "aarch64" ]; then
            chmod +x ./dist/upid-linux-arm64
            ./dist/upid-linux-arm64 --help
          else
            chmod +x ./dist/upid-linux-x86_64
            ./dist/upid-linux-x86_64 --help
          fi

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/upid-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
