name: Build and Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller rich click requests pyyaml

      - name: Build Linux x86_64 binary
        run: |
          pyinstaller --onefile --name upid-linux-x86_64 upid_main.py

      - name: Test Linux binary
        run: |
          chmod +x ./dist/upid-linux-x86_64
          ./dist/upid-linux-x86_64 --help

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/upid-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller rich click requests pyyaml

      - name: Build macOS arm64 binary
        run: |
          pyinstaller --onefile --name upid-darwin-arm64 upid_main.py

      - name: Test macOS binary
        run: |
          chmod +x ./dist/upid-darwin-arm64
          ./dist/upid-darwin-arm64 --help

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/upid-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows-x86_64:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller rich click requests pyyaml

      - name: Build Windows binary
        run: |
          pyinstaller --onefile --name upid-windows-x86_64 upid_main.py

      - name: Test Windows binary
        run: |
          ./dist/upid-windows-x86_64.exe --help

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/upid-windows-x86_64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux-arm64:
    # Optional: remove this if you don't have ARM64 runners
    runs-on: ubuntu-latest
    container:
      image: arm64v8/python:3.11
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          apt update
          apt install -y gcc build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller rich click requests pyyaml

      - name: Build Linux ARM64 binary
        run: |
          pyinstaller --onefile --name upid-linux-arm64 upid_main.py

      - name: Test Linux ARM64 binary
        run: |
          chmod +x ./dist/upid-linux-arm64
          ./dist/upid-linux-arm64 --help

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/upid-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
