name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: false
        default: 'v1.0.1'

jobs:
  release-notes-and-publish:
    name: Release Notes and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # NOTE: All build and packaging is handled by the build-binaries.yml workflow.
      # This workflow only creates release notes and publishes the release.

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag_name=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Release Notes
        run: |
          VERSION=${{ steps.version.outputs.version }}
          cat > release_notes.md << EOF
          # UPID CLI $VERSION
          
          ## 🚀 Production-Ready Kubernetes Cost Optimization Platform
          
          ### What's New
          - See the release summary and changelog for details.
          
          ### Installation (kubectl-style)
          
          **Linux:**
          \`\`\`bash
          curl -LO "https://github.com/\${{ github.repository }}/releases/download/$VERSION/upid-linux-amd64"
          chmod +x upid-linux-amd64
          sudo mv upid-linux-amd64 /usr/local/bin/upid
          \`\`\`
          
          **macOS:**
          \`\`\`bash
          curl -LO "https://github.com/\${{ github.repository }}/releases/download/$VERSION/upid-darwin-amd64"
          chmod +x upid-darwin-amd64
          sudo mv upid-darwin-amd64 /usr/local/bin/upid
          \`\`\`
          
          **Windows:**
          \`\`\`powershell
          Invoke-WebRequest -Uri "https://github.com/\${{ github.repository }}/releases/download/$VERSION/upid-windows-amd64.exe" -OutFile "upid.exe"
          Move-Item upid.exe "\$env:USERPROFILE\bin\upid.exe"
          \`\`\`
          
          ### Documentation
          - [User Manual](https://github.com/\${{ github.repository }}/blob/main/docs/USER_MANUAL.md)
          - [API Reference](https://github.com/\${{ github.repository }}/blob/main/docs/API_REFERENCE.md)
          - [Command Reference](https://github.com/\${{ github.repository }}/blob/main/docs/COMMAND_REFERENCE.md)
          
          **🎯 Ready for Production Deployment and Client Testing!**
          EOF

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          name: UPID CLI ${{ steps.version.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}